services:
  - type: web
    name: totem-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        value: bot_users.db

  - type: web
    name: totem-bot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_webhook.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BACKEND_URL
        fromService:
          type: web
          name: totem-backend
          property: host